name: Lint & Build

on:
  pull_request:
    branches: [ main, dev,DEV]
  push:
    branches: [ main, dev,DEV]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: canvas

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: canvas/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
      - run: pnpm biome check .
      - run: pnpm build
